engines:
  scss-lint:
    enabled: true
    checks:
      SelectorFormat:
        enabled: false
  eslint:
    enabled: true
ratings:
  paths:
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.css"
  - "**.scss"
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/
- db/
- script/
- vendor/
